# Generated by Django 5.1.7 on 2025-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Enter technologies separated by commas', max_length=500),
        ),
    ]
